name: generate-builds

on:
  push:
  pull_request:

jobs:
  Windows:

  
    name: build-windows
    runs-on: windows-latest
    
    steps:
      - name : Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name : Checkout
        uses: actions/checkout@v1
        
      - name : Build
        run: |
          MSBuild.exe Project1.sln 
