name: generate-builds

on:
  push:
  pull_request:

jobs:
  Windows:

  
    name: build-windows
    runs-on: windows-latest
    
    steps:
      - name : Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name : Checkout
        uses: actions/checkout@v1
        with: 
            submodules: 'true'
      
      - name : BuildSDL
        run: |
          MSBuild.exe SDL\VisualC\SDL.sln /p:Configuration=Release /p:Platform=x64 -m /target:SDL3
        
      - name : Build
        run: |
          MSBuild.exe Project1.sln 
