name: generate-builds

on:
  push:
  pull_request:

jobs:
  Windows:

    name: build-windows
    runs-on: windows-latest
    
    steps:
      - name : Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name : Checkout
        uses: actions/checkout@v1
        with: 
            submodules: 'true'
      
      - name : BuildSDL
        run: |
          MSBuild.exe SDL\VisualC\SDL.sln /p:Configuration=Release /p:Platform=x64 -m /target:SDL3
        
      - name : Build
        run: |
          MSBuild.exe Project1.sln 
  
  Linux:
    name: build-linux
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v1

      - name : InstallSDL
        run: |
          sudo apt install libsdl2-dev

      - name : Build
        run: |
          make -j $(nproc) 
